### ISSUE TITLE
Download all the photos

### ISSUE THREAD

**Issue by maxys92** [seeya/Facebook-Album-Downloader#1]
Just wanted to know if it would be possible to download all the photos from certain profile o every photo when some person has been etiquette?

**Comment by seeya** [comment]
What do you mean "has been etiquette"? As long as you have the link and permission to view it'll be possible to download

**Comment by maxys92** [comment]
Sorry, the translation was wrong. I was trying to ask if it would be possible to download all "X's Photos" instead of albums individually. For example, every photo seeya is tagged in or you have uploaded instead of one album at the time

**Comment by seeya** [comment]
Currently it's only possible to download an album at a time.
