### ISSUE TITLE
Can't open photos

### ISSUE THREAD

**Issue by maxys92** [seeya/Facebook-Album-Downloader#4]
Now, I can download the photos. However, most of them doesn't load. When I open those photos that doesn't load with Photo Viewer it says: "Windows photo viewer can't open this picture because either photo viewer doesn't support this file format or you don't have the latest updates to photo viewer".

**Comment by seeya** [comment]
What are the file sizes of the downloaded photos? It's working on my side, is the album link private? If not I can take a look.

**Comment by maxys92** [comment]
The downloaded files are around 27 and 27,2 KB. I've tried with two albums, both private.

**Comment by seeya** [comment]
Fixed the private album problem. I was using a non-authenticated browser to download the private links. Please try the latest version and let me know if it works for you. 8c63816f38501c0f31e638e8799a5717e8fc36fa

**Comment by maxys92** [comment]
Flawlessly. Thanks.
